spring:
  application:
    name: learn-jpa
  datasource:
    url: jdbc:mysql://172.16.2.132:3306/test_fq_2
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  rabbitmq:
    addresses: 172.16.2.132:5672
    virtual-host: vhost_fq
    requested-heartbeat: 15
    username: accounting
    password: accounting
    cache:
      channel:
        size: 300
      connection:
        mode: CHANNEL
    template:
      retry:
        enabled: true
        initial-interval: 15000
        max-interval: 30000
        max-attempts: 5
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5
          max-interval: 30000
          initial-interval: 15000
        prefetch: 1
        transaction-size: 1
        concurrency: 1
        max-concurrency: 3
        idle-event-interval: 60000
        default-requeue-rejected: false



server:
  port: 8080
  context-path: /learn-springBatch


logging:
  level:
    root: info