activity:
  datasource:
    type: com.alibaba.druid.pool.xa.DruidXADataSource
    url: jdbc:mysql://127.0.0.1:3306/data-refill-center-activity?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 50
    minIdle: 50
    maxActive: 500
    maxWait: 60000 
    timeBetweenEvictionRunsMillis: 60000  
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false  
    testOnReturn: false  
    poolPreparedStatements: true 
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
coupon:
  datasource:
    type: com.alibaba.druid.pool.xa.DruidXADataSource
    url: jdbc:mysql://127.0.0.1:3306/data-refill-center-coupon?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 50
    minIdle: 50
    maxActive: 500
    maxWait: 60000 
    timeBetweenEvictionRunsMillis: 60000  
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false  
    testOnReturn: false  
    poolPreparedStatements: true 
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
credit:
  datasource:
    type: com.alibaba.druid.pool.xa.DruidXADataSource
    url: jdbc:mysql://127.0.0.1:3306/data-refill-center-credit?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 50
    minIdle: 50
    maxActive: 500
    maxWait: 60000 
    timeBetweenEvictionRunsMillis: 60000  
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false  
    testOnReturn: false  
    poolPreparedStatements: true 
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
finance:
  datasource:
    type: com.alibaba.druid.pool.xa.DruidXADataSource
    url: jdbc:mysql://127.0.0.1:3306/data-refill-center-finance?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 50
    minIdle: 50
    maxActive: 500
    maxWait: 60000 
    timeBetweenEvictionRunsMillis: 60000  
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false  
    testOnReturn: false  
    poolPreparedStatements: true 
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
lottery:
  datasource:
    type: com.alibaba.druid.pool.xa.DruidXADataSource
    url: jdbc:mysql://127.0.0.1:3306/data-refill-center-lottery?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 50
    minIdle: 50
    maxActive: 500
    maxWait: 60000 
    timeBetweenEvictionRunsMillis: 60000  
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false  
    testOnReturn: false  
    poolPreparedStatements: true 
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
order:
  datasource:
    type: com.alibaba.druid.pool.xa.DruidXADataSource
    url: jdbc:mysql://127.0.0.1:3306/data-refill-center-order?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 50
    minIdle: 50
    maxActive: 500
    maxWait: 60000 
    timeBetweenEvictionRunsMillis: 60000  
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false  
    testOnReturn: false  
    poolPreparedStatements: true 
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
package:
  datasource:
    type: com.alibaba.druid.pool.xa.DruidXADataSource
    url: jdbc:mysql://127.0.0.1:3306/data-refill-center-package?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 50
    minIdle: 50
    maxActive: 500
    maxWait: 60000 
    timeBetweenEvictionRunsMillis: 60000  
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false  
    testOnReturn: false  
    poolPreparedStatements: true 
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    
jta:
  log-dir: classpath:tx-logs
  transaction-manager-id: txManager