logging:
  level.root: info

spring:
  datasource:
    url: jdbc:mysql://10.255.33.35:3321/fengqing
    username: root
    password: sdfjo29@2
  profiles:
    active: dev


# 有配置PerformanceInterceptor 就无需开启这个
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0